##  1. Setting up numpy

## Importing NumPy

In [1]:
import numpy as np
np.random.seed(0)
np.version.version

'1.16.2'

## 2. Vector arrays

In [4]:
e1=np.array([1,0,0])
e2=np.array([0,1,0])
e3=np.array([0,0,1])

print('e1 =',e1)
print('e2 =',e2)
print('e3 =',e3)

e1 = [1 0 0]
e2 = [0 1 0]
e3 = [0 0 1]


## Dot product

## The dot product of two given array is defined as a.b =|a||b|cos {$\theta$}

So because orthogonal vector arrays have $\theta$ =90$^{\circ}$ so we have cos 90$^{\circ}$=0

Therefore, e1.e2=e2.e3=e1.e3=0

In [3]:
e1=np.array([1,0,0])
e2=np.array([0,1,0])
e3=np.array([0,0,1])

print('e1.e2 =',np.dot(e1,e2))
print('e1.e3 =',np.dot(e1,e3))
print('e2.e3 =',np.dot(e2,e3))

e1.e2 = 0
e1.e3 = 0
e2.e3 = 0


Vector arrays that are the same $\theta$ =0$^{\circ}$ so we have cos 0$^{\circ}$=1

Therefore. e1.e1=e2.e2=e3.e3=1

In [8]:
print('e1.e1 =',np.dot(e1,e1))
print('e2.e2 =',np.dot(e2,e2))
print('e3.e3 =',np.dot(e3,e3))

e1.e1 = 1
e2.e2 = 1
e3.e3 = 1


In [9]:
a1=3
e1=np.array([1,0,0])
print('a1*e1 =',a1*e1)

a1*e1 = [3 0 0]


In [11]:
a1=3
a2=1
a3=4
a=a1*e1 + a2 *e2 + a3 *e3
print('a = a1*e1 + a2*e1 + a3*e1 =',a)

a = a1*e1 + a2*e1 + a3*e1 = [3 1 4]


In [13]:
components=[a1,a2,a3]
vectors=[e1,e2,e3]
a=np.zeros(3)
for i in range(len(components)):
    a+=components[i] * vectors[i]
print('sum of {i=1} to {3} of {ai ei} =',a)


sum of {i=1} to {3} of {ai ei} = [3. 1. 4.]


In [20]:
a=np.zeros(3)
for component,vector in zip(components,vectors):
    a+=component*vector
print('Sum of each {component} in {components} =',a)

Sum of each {component} in {components} = [3. 1. 4.]


### Many ways below

In [15]:
u_components=[3,1,4]
v_components=[1,5,9]

u=u_components[0] * e1 + u_components[1] * e2 +u_components[2] *e3
v=v_components[0] * e1 + v_components[1] * e2 +v_components[2] *e3
result=np.dot(u,v)
print(result)

44


In [16]:
e=[e1,e2,e3]

result=0
for i in range(len(e)):
    for j in range(len(e)):
        result+=u_components[i] * v_components[j] * (np.dot(e[i],e[j]))
print(result)

44


In [17]:
u = np.array(u_components)
v = np.array(v_components)

result=u[0]*v[0] + u[1]*v[1] + u[2]*v[2]

print(result)

44


In [18]:
result=0
for i in range(len(u)):
    result+=u[i]*v[i]
print(result)

44


In [19]:
result=np.dot(u,v)
print(result)

44


#### kronecker delta

In [22]:
def kron(i,j):
    if i==j:
        return 1
    else:
        return 0
print(kron(1,1))
print(kron(1,2))

1
0


In [23]:
e=[e1,e2,e3]
for i in range(len(e)):
    for j in range(len(e)):
        print(np.dot(e[i],e[j]),'=',kron(i,j))

1 = 1
0 = 0
0 = 0
0 = 0
1 = 1
0 = 0
0 = 0
0 = 0
1 = 1


## 3.Matrix Array Notation

In [26]:
# Create a random 3 x 1 random matrix array from uniform distribution from 0 to 1
v=np.random.random((3,1))

#Transposing it yields 1 x 3 matrix array
print('v =\n',v)
print('v.T =\n',v.T)

v =
 [[0.54488318]
 [0.4236548 ]
 [0.64589411]]
v.T =
 [[0.54488318 0.4236548  0.64589411]]


In [30]:
# Create a random 3 x 1 random matrix array from 0 to 1
u=np.random.random((3,1))

#Transposing it yields 1 X 3 matrix array
print('u =\n',u)
print('u^T =\n',u.T)

u =
 [[0.38344152]
 [0.79172504]
 [0.52889492]]
u^T =
 [[0.38344152 0.79172504 0.52889492]]


##### an example of matrix multiplication

In [33]:
result=np.matmul(u.T,v)
print('u^T.v =\n',result)

u^T.v =
 [[0.88595906]]


#### The 3 X 3 matrix array

In [34]:
I=np.eye(3)

print('I =\n',I)

I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [41]:
u=np.random.random((3,1))
result=np.dot(I,u)

print('u =\n',u)
print('I =\n',I)
print('u.I =\n',result)

u =
 [[0.26455561]
 [0.77423369]
 [0.45615033]]
I =
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
u.I =
 [[0.26455561]
 [0.77423369]
 [0.45615033]]


In [45]:
u=np.array([[1,2,3]])
v=np.array([[4,5,6]])

result=np.matmul(u.T,v)
print('u^T.v=\n',result)

u^T.v=
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [49]:
#Squeezing the matrix (2D) arrays makes them vector 1D array
u=u.squeeze()
v=v.squeeze()
result=np.tensordot(u,v,axes=0)
print('uXv =\n',result)

uXv =
 [[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [55]:
Q=np.random.randint(9,size=(3,3))
u=np.array([[1],
            [2],
            [3]])
result=np.matmul(Q,u)
print('Q =\n',Q)
print('u =\n',u)
print('Q.u =\n',result)

Q =
 [[4 2 0]
 [3 2 0]
 [7 5 0]]
u =
 [[1]
 [2]
 [3]]
Q.u =
 [[ 8]
 [ 7]
 [17]]


In [56]:
A=np.random.randint(9,size=(3,3))
B=np.random.randint(9,size=(3,3))

result=np.dot(A,B).T

print('A =\n',A)
print('B =\n',B)
print('(A.B)^T',result)

A =
 [[2 7 2]
 [2 3 3]
 [2 3 4]]
B =
 [[1 2 1]
 [4 6 8]
 [2 3 0]]
(A.B)^T [[34 20 22]
 [52 31 34]
 [58 26 26]]


In [57]:
result=np.dot(B.T,A.T)
print('A^T =\n',A.T)
print('B^T =\n',B.T)
print('B^T.A^T =\n',result)

A^T =
 [[2 2 2]
 [7 3 3]
 [2 3 4]]
B^T =
 [[1 4 2]
 [2 6 3]
 [1 8 0]]
B^T.A^T =
 [[34 20 22]
 [52 31 34]
 [58 26 26]]


## 4. Tensor Arrays

In [63]:
A=np.random.randint(9,size=(3))
B=np.random.randint(9,size=(4,4))

print('A =\n',A)
print('B =\n',B)
print('A x B =\n',np.tensordot(A,B,axes=0))

A =
 [1 1 0]
B =
 [[3 8 8 4]
 [4 0 3 7]
 [3 2 1 1]
 [2 1 4 2]]
A x B =
 [[[3 8 8 4]
  [4 0 3 7]
  [3 2 1 1]
  [2 1 4 2]]

 [[3 8 8 4]
  [4 0 3 7]
  [3 2 1 1]
  [2 1 4 2]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]


#### consider this list of matrices

In [70]:
a1=np.array([np.array([1,2,3,6]),
             np.array([4,5,6,7]),
             np.array([7,8,9,1])
            ])
a2=np.array([np.array([1,2,3,4]),
             np.array([5,6,7,8])
            ])
a3=np.array([np.array([1,2,3,4]),
             np.array([5,6,7,8]),
             np.array([2,8,3,1]),
             np.array([9,4,6,1])
            ])
A=np.array([a1,a2,a3])
print('A =\n',A.T)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]


### How to subset the first two elements to make a tensor array

In [71]:
A1=[record[:2] for record in A ]
A1=np.array(A1)
print('A =\n',A)
print('A1 =\n',A1)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]
A1 =
 [[[1 2 3 6]
  [4 5 6 7]]

 [[1 2 3 4]
  [5 6 7 8]]

 [[1 2 3 4]
  [5 6 7 8]]]


### How to subset the first two elements to make a tensor array

In [72]:
A1=[record[:-2] for record in A ]
A1=np.array(A1)
print('A =\n',A)
print('A1 =\n',A1)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]
A1 =
 [array([[1, 2, 3, 6]]) array([], shape=(0, 4), dtype=int32)
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])]


### How to pad at the bottom to make a tensor array

In [76]:
pad_below1 = 4 - len(a1)
pad_below2 = 4 - len(a2)
pad_below3 = 4 - len(a3)

pad_above = 0
pad_left  = 0
par_right = 0
n_add=[((pad_above,pad_below1),(pad_left, par_right)),
       ((pad_above,pad_below2),(pad_left, par_right)),
       ((pad_above,pad_below3), (pad_left, par_right))]
A3=[np.pad(A[i],pad_width=n_add[i],mode='constant',constant_values=0) for i in range(3)]
A3=np.array(A3)

print('A =\n',A)
print('A3 =\n',A3)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]
A3 =
 [[[1 2 3 6]
  [4 5 6 7]
  [7 8 9 1]
  [0 0 0 0]]

 [[1 2 3 4]
  [5 6 7 8]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 2 3 4]
  [5 6 7 8]
  [2 8 3 1]
  [9 4 6 1]]]


#### How to pad at the top to make a tensor array

In [77]:
pad_above1 = 4 - len(a1)
pad_above2 = 4 - len(a2)
pad_above3 = 4 - len(a3)

pad_below = 0
pad_left  = 0
par_right = 0
n_add=[((pad_below,pad_above1),(pad_left, par_right)),
       ((pad_below,pad_above2),(pad_left, par_right)),
       ((pad_below,pad_above3), (pad_left, par_right))]
A4=[np.pad(A[i],pad_width=n_add[i],mode='constant',constant_values=0) for i in range(3)]
A4=np.array(A3)

print('A =\n',A)
print('A3 =\n',A4)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]
A3 =
 [[[1 2 3 6]
  [4 5 6 7]
  [7 8 9 1]
  [0 0 0 0]]

 [[1 2 3 4]
  [5 6 7 8]
  [0 0 0 0]
  [0 0 0 0]]

 [[1 2 3 4]
  [5 6 7 8]
  [2 8 3 1]
  [9 4 6 1]]]


#### How to vertically stack the 3D object to make a2D matrix array

In [78]:
A5 = np.vstack(A)

print('A =\n',A)
print('A5 =\n',A5)

A =
 [array([[1, 2, 3, 6],
       [4, 5, 6, 7],
       [7, 8, 9, 1]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
 array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 8, 3, 1],
       [9, 4, 6, 1]])]
A5 =
 [[1 2 3 6]
 [4 5 6 7]
 [7 8 9 1]
 [1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]
 [2 8 3 1]
 [9 4 6 1]]
